---
# tasks file for build WordPress

- name: install php
  yum: "name={{item}} state=present"
  with_items:
    - curl
    - curl-devel
    - php-gd
    - php-mysql
    - ImageMagick
    - mariadb
  tags:
    - build

- name: download wp-cli
  get_url: >
    url=https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar 
    dest=/usr/local/bin/wp
  tags:
    - build

- name: update permissions of wp-cli to allow anyone to execute it (should be only for local install!)
  file: path=/usr/local/bin/wp mode="0700"
  tags:
    - build

- name: Download wordpress into /srv/wordpress using wp-cli command as the wordpress user
  command: >
    wp core download --allow-root
    --version={{ wordpress_version }}
    --path=/srv/wordpress/
    creates=/srv/wordpress/wp-includes
  tags:
    - build

- name: Setup CMD shell script
  template: src=start.sh.j2 dest=/usr/local/bin/start.sh mode=0700
  tags:
    - build

- name: Set some parameters at /etc/php.ini
  lineinfile: >
    dest=/etc/php.ini 
    state=present 
    regexp=' *;? *({{ item.key }} *=) *(.*)' 
    line='\1 {{item.value}}' 
    backrefs=yes
  with_dict:
    cgi\.fix_pathinfo: 0
    allow_url_fopen: Off
  tags:
    - build

- name: Setup PHP config file
  template: src=www.conf.j2 dest=/etc/php-fpm.d/www.conf mode=0644
  tags:
    - build
